# Generated by Django 3.0.4 on 2020-04-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent_main', '0004_auto_20200331_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='torrent_files'),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='torrent_images'),
        ),
    ]
