# Generated by Django 3.0.4 on 2020-05-15 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torrent_main', '0006_auto_20200515_1639'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TorrentFilesInfo',
            new_name='TorrentFileInfo',
        ),
    ]
