# Generated by Django 3.0.4 on 2020-05-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent_main', '0008_torrent_info_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrent',
            name='total_size',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
