# Generated by Django 3.0.4 on 2020-05-15 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torrent_main', '0009_auto_20200515_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='torrent',
            old_name='leechers',
            new_name='leeches',
        ),
    ]
