# Generated by Django 3.0.4 on 2020-05-16 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torrent_main', '0010_auto_20200515_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='torrent',
            old_name='link',
            new_name='url',
        ),
    ]
